name:                 sigil-hs
version:              0.2.0.0
visibility:           public
id:                   sigil-hs-0.2.0.0-2Y4QyDdYB6rJy0QAnSbj4W
key:                  sigil-hs-0.2.0.0-2Y4QyDdYB6rJy0QAnSbj4W
license:              MIT
synopsis:             Sigil image codec — Haskell reference implementation
abi:                  8e3969d269d9a34456bdde9c1f295fdf
exposed:              True
exposed-modules:
    Sigil Sigil.Codec.Pipeline Sigil.Codec.Predict Sigil.Codec.Rice
    Sigil.Codec.Token Sigil.Codec.ZigZag Sigil.Core.Chunk
    Sigil.Core.Error Sigil.Core.Types Sigil.IO.Convert Sigil.IO.Reader
    Sigil.IO.Writer

hidden-modules:       Paths_sigil_hs
import-dirs:
    "/Users/dennis/programming projects/imgcompressor/sigil-hs/.stack-work/install/x86_64-osx/a45f360f33cb8974d4454cd45fed3f1d94973137487f27ff963810900d2a7567/9.6.6/lib/x86_64-osx-ghc-9.6.6/sigil-hs-0.2.0.0-2Y4QyDdYB6rJy0QAnSbj4W"

library-dirs:
    "/Users/dennis/programming projects/imgcompressor/sigil-hs/.stack-work/install/x86_64-osx/a45f360f33cb8974d4454cd45fed3f1d94973137487f27ff963810900d2a7567/9.6.6/lib/x86_64-osx-ghc-9.6.6/sigil-hs-0.2.0.0-2Y4QyDdYB6rJy0QAnSbj4W"

library-dirs-static:
    "/Users/dennis/programming projects/imgcompressor/sigil-hs/.stack-work/install/x86_64-osx/a45f360f33cb8974d4454cd45fed3f1d94973137487f27ff963810900d2a7567/9.6.6/lib/x86_64-osx-ghc-9.6.6/sigil-hs-0.2.0.0-2Y4QyDdYB6rJy0QAnSbj4W"

dynamic-library-dirs:
    "/Users/dennis/programming projects/imgcompressor/sigil-hs/.stack-work/install/x86_64-osx/a45f360f33cb8974d4454cd45fed3f1d94973137487f27ff963810900d2a7567/9.6.6/lib/x86_64-osx-ghc-9.6.6"

data-dir:
    "/Users/dennis/programming projects/imgcompressor/sigil-hs/.stack-work/install/x86_64-osx/a45f360f33cb8974d4454cd45fed3f1d94973137487f27ff963810900d2a7567/9.6.6/share/x86_64-osx-ghc-9.6.6/sigil-hs-0.2.0.0"

hs-libraries:         HSsigil-hs-0.2.0.0-2Y4QyDdYB6rJy0QAnSbj4W
depends:
    JuicyPixels-3.3.9-8Lq1qIq7fIG6tpfvhLR4Y4 base-4.18.2.1
    binary-0.8.9.1 bytestring-0.11.5.3 directory-1.3.8.5
    filepath-1.4.300.1 text-2.0.2 time-1.12.2
    vector-0.13.1.0-Aqc2YUE1Egs5WmXVMbcJ5T

haddock-interfaces:
    "/Users/dennis/programming projects/imgcompressor/sigil-hs/.stack-work/install/x86_64-osx/a45f360f33cb8974d4454cd45fed3f1d94973137487f27ff963810900d2a7567/9.6.6/doc/sigil-hs-0.2.0.0/sigil-hs.haddock"

haddock-html:
    "/Users/dennis/programming projects/imgcompressor/sigil-hs/.stack-work/install/x86_64-osx/a45f360f33cb8974d4454cd45fed3f1d94973137487f27ff963810900d2a7567/9.6.6/doc/sigil-hs-0.2.0.0"
